services:
  - type: web
    name: quickbhandar
    env: docker
    plan: free
    branch: main
    buildCommand: "dotnet publish -c Release -o out"
    startCommand: "dotnet out/QuickBhandarWeb.dll"
    autoDeploy: true
